modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="modtester"
version="1.0.0"
displayName="ModTester"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="benjaminoler, MCreator"

[[dependencies.modtester]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




